name = "api"
main = "src/index.ts"
compatibility_date = "2025-01-27"

compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "workout-tracker"
database_id = "14dc62f5-3020-4c0a-9598-2da87319eb80"
migrations_dir = "src/db/migrations"
preview_database_id = "c8f83468-3e06-4b7f-924a-dd3b62e6f67f"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
