name: API Deploy PREVIEW

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  generate-token:
    runs-on: ubuntu-latest
    name: Generate API Token
    outputs:
      uuid: ${{ steps.generate-uuid.outputs.uuid }}
    steps:
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: ${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Preview
    needs: generate-token
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/api'
          precommands: echo "API_TOKEN is ${{ needs.generate-token.outputs.uuid }}"
          secrets: |
            API_TOKEN=${{ needs.generate-token.outputs.uuid }}
          command: versions upload
